services:
  minehututils:
#    image: ghcr.io/santiomc/minehututils:master
    build:
        context: .
        dockerfile: Dockerfile
    container_name: minehututils
    restart: always
    volumes:
      - ./data:/app/data
    env_file: .env
